{
   
    "routes": [
      {
        "src": "/products",
        "dest": "index.js"
      },
      {
        "src": "/products/(.*)",
        "dest": "index.js"
      },
      {
        "src": "/add",
        "dest": "build/index.html"
      },
      {
        "src": "/",
        "dest": "build/index.html"
      },
      {
        "src": "/(.+)",
        "dest": "build/$1"
      }
    ]
  }