[build]
  command = "npm run build"  # Replace with the command to build your Express.js app
  publish = "build"  # Replace with the path to the build artifacts

[build.environment]
  NODE_ENV = "production"  # Set Node.js environment to production

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200